--<?php echo $this->aData['boundary'].'
'; ?>
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Very mitered Ms / Mr <?php echo $this->aData['user']->get('name'). ' '.$this->aData['user']->get('surname'); ?>,

Your Grohe Display-Factory-Account request was granted.<br />


Your login is: <?php echo $this->aData['user']->get('mail'); ?>
Your password is:</b> <?php echo $this->aData['password']; ?>


Please change your password immediately under the "My Account" settings.
Your way to the display factory: http://grohe2.hoehne-media.de

--<?php echo $this->aData['boundary'].'
'; ?>
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit


<html>
	<head>
		<style>
			body{
				font-family: Verdana;
				color:#000000;
			}

		</style>
	</head>
	<body>
	    Very mitered Ms / Mr <?php echo $this->aData['user']->get('name'). ' '.$this->aData['user']->get('surname'); ?>,<br />
	    <br />
	    Your Grohe Display-Factory-Account request was granted.<br />
	    <br />

	    <b>Your login is:</b> <?php echo $this->aData['user']->get('mail'); ?><br />
	    <b>Your password is:</b> <?php echo $this->aData['password']; ?><br /><br />

	    Please change your password immediately under the "My Account" settings.<br /><br />
	    <a href="http://grohe2.hoehne-media.de/">Your way to the display factory</a>
	</body>
</html>

--<?php echo $this->aData['boundary']; ?>--
