--<?php echo $this->aData['boundary'].'
'; ?>
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

New Display Request from:

User-Request Information:
Name: <?php echo $this->aData['user']->get('name'); ?>
Surame: <?php echo $this->aData['user']->get('surname'); ?></td>
Department: <?php echo $this->aData['user']->get('department'); ?>
Street: <?php echo $this->aData['user']->get('street'); ?></td>
Zipcode: <?php echo $this->aData['user']->get('zipcode'); ?>
City: <?php echo $this->aData['user']->get('city'); ?>
Country: <?php echo $this->aData['user']->get('country'); ?>
Phone: <?php echo $this->aData['user']->get('phone'); ?>
Fax: <?php echo $this->aData['user']->get('fax'); ?>
E-Mail-Address: <?php echo $this->aData['user']->get('mail'); ?>


--<?php echo $this->aData['boundary'].'
'; ?>
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit


<html>
	<head>
		<style>
			body{
				font-family: Verdana;
				color:#000000;
			}

		</style>
	</head>
	<body>
		<h2>New Display Request from:</h2>
	    <b>User-Request Information:</b><br />
	    <table border="1">
	      <tr>
	        <td><b>Name:</b></td>
	        <td><?php echo $this->aData['user']->get('name'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Surame:</b></td>
	        <td><?php echo $this->aData['user']->get('surname'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Department:</b></td>
	        <td><?php echo $this->aData['user']->get('department'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Street:</b></td>
	        <td><?php echo $this->aData['user']->get('street'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Zipcode:</b></td>
	        <td><?php echo $this->aData['user']->get('zipcode'); ?></td>
	      </tr>
	      <tr>
	        <td><b>City:</b></td>
	        <td><?php echo $this->aData['user']->get('city'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Country:</b></td>
	        <td><?php echo $this->aData['user']->get('country'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Phone:</b></td>
	        <td><?php echo $this->aData['user']->get('phone'); ?></td>
	      </tr>
	      <tr>
	        <td><b>Fax:</b></td>
	        <td><?php echo $this->aData['user']->get('fax'); ?></td>
	      </tr>
	      <tr>
	        <td><b>E-Mail-Address:</b> </td>
	        <td><?php echo $this->aData['user']->get('mail'); ?></td>
	      </tr>
	    </table>
	    
	    <h2>Request Text:</h2>
	    <p><?php echo $this->aData['requestText']; ?></p>
	    
	    <?php if($this->aData['image']): ?>
	    <h2>Link to Top Sign</h2>
	    <a href="<?php echo cConfig::getInstance()->get('domain'); ?>api/topsign/usertopsigns/<?php echo $this->aData['image']->get('path'); ?>" />Custom Topsign</a>
	    <?php endif; ?>
	</body>
</html>

--<?php echo $this->aData['boundary']; ?>--
